### ISSUE TITLE
evaluate时的问题

### ISSUE THREAD

**Issue by peterwan1** [xxw11/AutoGPTQ_QALoRA#1]
你好！
在QA-LoRA中，我在merge前把model的qzeros用qlinear里面的代码decode成了浮点型，之后还保存在了qzeros中。然后我把qlinear改成了你这里的版本。之后调用AutoGPTQForCausalLM.from_quantized加载模型在mmlu上评测，但是结果很差，基本上就是1/4的随机值。我试了merge前的quantized model，结果是正常的。
我感觉是merged model的weight没有被dequantize？还是其他的什么原因呢？应该模型训练的问题不至于差别这么大呀。
想问一下评测的时候你是怎么加载模型的呀，或者能不能告知一下你quantize、qalora、merge、evaluate这四步都使用的是哪个版本的代码？
感谢！

**Comment by peterwan1** [comment]
@xxw11

**Comment by wxx0912** [comment]
你好，请问你是如何把model的qzeros用qlinear里面的代码decode成了浮点型？
我使用如下代码进行合并，但在调用AutoGPTQForCausalLM.from_quantized加载模型时出现了“safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge”这个错误。
import torch
import numpy as np
from safetensors.torch import load_file
model_path = './Qwen7B-quant-4b-g128/gptq_model-4bit-128g.safetensors'
lora_path = './output_2b-g128/checkpoint-1000/adapter_model/adapter_model.bin'
merged_path = './lora_save/Qwen7B-quant-2b-g128_merged_model.safetensors'
scale = 16 /64
group_size = 128


def decode_qzeros(qzeros, bits=4):
    if bits != 4:
        raise ValueError("This function is only implemented for 4-bit quantization.")
    
    # 确保输入是 PyTorch Tensor
    if not isinstance(qzeros, torch.Tensor):
        qzeros = torch.tensor(qzeros)
    
    # 创建偏移量张量，形状为 (1, 1, 8)
    offsets = torch.arange(8, device=qzeros.device).view(1, 1, -1)
    
    # 扩展 qzeros 维度以便广播，形状变为 (batch, cols, 1)
    q = qzeros.unsqueeze(-1)
    
    # 计算每个 4-bit 的值，形状 (batch, cols, 8)
    shifted = torch.bitwise_right_shift(q, 4 * offsets)
    zeros = torch.bitwise_and(shifted, 0xF)
    
    # 调整形状为 (batch, cols*8)
    zeros = zeros.view(qzeros.size(0), -1)
    
    # 转换为 float16类型 返回
    return zeros.to(torch.float16)


model = load_file(model_path, device='cpu')
lora = torch.load(lora_path, map_location='cpu')
tmp_keys = [key[17:-14] for key in lora.keys() if 'lora_A' in key]
for tmp_key in tmp_keys:

    model[tmp_key+'.qzeros'] = decode_qzeros(model[tmp_key+'.qzeros'])

    model[tmp_key+'.qzeros'] -= (lora['base_model.model.'+tmp_key+'.lora_B.weight'] @ lora['base_model.model.'+tmp_key+'.lora_A.weight']).t() * scale / group_size /model[tmp_key+'.scales']
    model[tmp_key+'.qzeros'] = encode_qzeros_4bit(model[tmp_key+'.qzeros'])


torch.save(model, merged_path)
不知道是否是因为我的qzeros解码成浮点型时出现了问题，所以我想知道下你是如何解码成浮点型的，如果你能回复我，我将非常感激！

**Comment by xxw11** [comment]
> 你好，请问你是如何把model的qzeros用qlinear里面的代码decode成了浮点型？ 我使用如下代码进行合并，但在调用AutoGPTQForCausalLM.from_quantized加载模型时出现了“safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge”这个错误。 import torch import numpy as np from safetensors.torch import load_file model_path = './Qwen7B-quant-4b-g128/gptq_model-4bit-128g.safetensors' lora_path = './output_2b-g128/checkpoint-1000/adapter_model/adapter_model.bin' merged_path = './lora_save/Qwen7B-quant-2b-g128_merged_model.safetensors' scale = 16 /64 group_size = 128
> 
> def decode_qzeros(qzeros, bits=4): if bits != 4: raise ValueError("This function is only implemented for 4-bit quantization.")
> 
> ```
> # 确保输入是 PyTorch Tensor
> if not isinstance(qzeros, torch.Tensor):
>     qzeros = torch.tensor(qzeros)
> 
> # 创建偏移量张量，形状为 (1, 1, 8)
> offsets = torch.arange(8, device=qzeros.device).view(1, 1, -1)
> 
> # 扩展 qzeros 维度以便广播，形状变为 (batch, cols, 1)
> q = qzeros.unsqueeze(-1)
> 
> # 计算每个 4-bit 的值，形状 (batch, cols, 8)
> shifted = torch.bitwise_right_shift(q, 4 * offsets)
> zeros = torch.bitwise_and(shifted, 0xF)
> 
> # 调整形状为 (batch, cols*8)
> zeros = zeros.view(qzeros.size(0), -1)
> 
> # 转换为 float16类型 返回
> return zeros.to(torch.float16)
> ```
> 
> model = load_file(model_path, device='cpu') lora = torch.load(lora_path, map_location='cpu') tmp_keys = [key[17:-14] for key in lora.keys() if 'lora_A' in key] for tmp_key in tmp_keys:
> 
> ```
> model[tmp_key+'.qzeros'] = decode_qzeros(model[tmp_key+'.qzeros'])
> 
> model[tmp_key+'.qzeros'] -= (lora['base_model.model.'+tmp_key+'.lora_B.weight'] @ lora['base_model.model.'+tmp_key+'.lora_A.weight']).t() * scale / group_size /model[tmp_key+'.scales']
> model[tmp_key+'.qzeros'] = encode_qzeros_4bit(model[tmp_key+'.qzeros'])
> ```
> 
> torch.save(model, merged_path) 不知道是否是因为我的qzeros解码成浮点型时出现了问题，所以我想知道下你是如何解码成浮点型的，如果你能回复我，我将非常感激！

你好，由于最近很忙我很久没有维护这个仓库及相关环境了，无法复现你的问题，如果你需要帮助可以留一个联系方式，我会尝试联系你 @fzuwxx

**Comment by wxx0912** [comment]
> > 你好，请问你是如何把model的qzeros用qlinear里面的代码decode成了浮点型？ 我使用如下代码进行合并，但在调用AutoGPTQForCausalLM.from_quantized加载模型时出现了“safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge”这个错误。 import torch import numpy as np from safetensors.torch import load_file model_path = './Qwen7B-quant-4b-g128/gptq_model-4bit-128g.safetensors' lora_path = './output_2b-g128/checkpoint-1000/adapter_model/adapter_model.bin' merged_path = './lora_save/Qwen7B-quant-2b-g128_merged_model.safetensors' scale = 16 /64 group_size = 128
> > def decode_qzeros(qzeros, bits=4): if bits != 4: raise ValueError("This function is only implemented for 4-bit quantization.")
> > ```
> > # 确保输入是 PyTorch Tensor
> > if not isinstance(qzeros, torch.Tensor):
> >     qzeros = torch.tensor(qzeros)
> > 
> > # 创建偏移量张量，形状为 (1, 1, 8)
> > offsets = torch.arange(8, device=qzeros.device).view(1, 1, -1)
> > 
> > # 扩展 qzeros 维度以便广播，形状变为 (batch, cols, 1)
> > q = qzeros.unsqueeze(-1)
> > 
> > # 计算每个 4-bit 的值，形状 (batch, cols, 8)
> > shifted = torch.bitwise_right_shift(q, 4 * offsets)
> > zeros = torch.bitwise_and(shifted, 0xF)
> > 
> > # 调整形状为 (batch, cols*8)
> > zeros = zeros.view(qzeros.size(0), -1)
> > 
> > # 转换为 float16类型 返回
> > return zeros.to(torch.float16)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > model = load_file(model_path, device='cpu') lora = torch.load(lora_path, map_location='cpu') tmp_keys = [key[17:-14] for key in lora.keys() if 'lora_A' in key] for tmp_key in tmp_keys:
> > ```
> > model[tmp_key+'.qzeros'] = decode_qzeros(model[tmp_key+'.qzeros'])
> > 
> > model[tmp_key+'.qzeros'] -= (lora['base_model.model.'+tmp_key+'.lora_B.weight'] @ lora['base_model.model.'+tmp_key+'.lora_A.weight']).t() * scale / group_size /model[tmp_key+'.scales']
> > model[tmp_key+'.qzeros'] = encode_qzeros_4bit(model[tmp_key+'.qzeros'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > torch.save(model, merged_path) 不知道是否是因为我的qzeros解码成浮点型时出现了问题，所以我想知道下你是如何解码成浮点型的，如果你能回复我，我将非常感激！
> 
> 你好，由于最近很忙我很久没有维护这个仓库及相关环境了，无法复现你的问题，如果你需要帮助可以留一个联系方式，我会尝试联系你 [@fzuwxx](https://github.com/fzuwxx)

您好，这是我的联系方式：13067493961（微信/手机号），如果可以的话我想请教你一些问题。
